"""
Calibration harness for _verify_summary_claims' 3-model consensus vote.

The entanglement pipeline trusts this vote to catch hallucinated claims in
generated project summaries (real motivating case: `tribe` was once
summarized as "likely a first-person shooter" with zero support in the
sampled content). That trust has never been measured -- only spot-checked
on a couple of cases. This harness measures it properly.

Method: injected-claim testing, not hand-labeling from scratch. For each
real project already in the index:
  1. Sample real chunks and generate a summary the normal way (same code
     path as the actual pipeline) -- this is the CLEAN case.
  2. Build a CORRUPTED twin by appending one fabricated, specific,
     plausible-sounding tech claim that is NOT supported by the samples.
  3. Run the consensus vote against both.
  4. A correct vote: clean -> not flagged, corrupted -> flagged.

This measures the vote's actual precision/recall on a task with known
ground truth, instead of trusting the heuristic on vibes. Caveat: the
"clean" label is itself generated by the same pipeline being tested, not
independently hand-verified -- so a clean case that the summarizer itself
subtly polluted would bias recall downward, not upward. This is a real
limitation, not swept under the rug.
"""
import json
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from trit_app import SearchEngine
from trit_entanglement import (
    INDEX_DIR, MODEL_PATH, MIN_CHUNKS_PER_PROJECT,
    group_chunks_by_project, get_chunk_path, get_chunk_preview,
    _call_ollama, _verify_summary_claims, _verify_summary_claims_v2, NON_PROJECT_HINTS,
)

sys.stdout.reconfigure(errors="replace")

# Specific, plausible-sounding, generic tech claims -- picked to sound like
# something a summarizer COULD plausibly assert, not absurd strawmen.
# Deliberately generic (not tailored per-project) so a model can't pass by
# just knowing what each project already is; it has to actually cross-check
# the claim against the shown samples.
FABRICATED_CLAIMS = [
    "The project uses a PostgreSQL database for persistent storage.",
    "This is a multiplayer online system with real-time networking over WebSockets.",
    "The code implements a REST API using the Flask framework.",
    "This project is written primarily in Rust for performance-critical sections.",
    "It integrates with AWS S3 for cloud file storage.",
    "The system is containerized and deployed via Docker.",
    "This is a machine learning pipeline built with PyTorch.",
    "The project includes a companion mobile app built with React Native.",
    "It uses OAuth2 for user authentication.",
    "The project ships with a Kubernetes deployment configuration.",
]


def sample_project(engine, project, chunk_indices, sample_n=8, seed=0):
    rng = np.random.default_rng(seed)
    idx = rng.choice(chunk_indices, size=min(sample_n, len(chunk_indices)), replace=False)
    samples = []
    for i in idx:
        path = get_chunk_path(engine, i)
        preview = get_chunk_preview(engine, i, chars=250)
        if preview:
            samples.append(f"{path}: {preview}")
    return samples


def generate_clean_summary(project, samples_text):
    prompt = (
        f"Here are code snippets sampled from a project called \"{project}\":\n\n"
        + samples_text
        + "\n\nBased ONLY on these real snippets, answer in 3 short sentences: "
        "(1) what kind of project is this, (2) what does it appear to do, "
        "(3) what is it likely for. Do not invent details not suggested by the snippets."
    )
    return _call_ollama(prompt)


def main():
    n_projects = int(sys.argv[1]) if len(sys.argv) > 1 else 8

    print("Loading OBSERVE index...")
    engine = SearchEngine()
    engine.load(INDEX_DIR, MODEL_PATH, lambda msg: print(f"  {msg}"))
    while not engine.ready:
        time.sleep(0.2)

    groups = group_chunks_by_project(engine)
    groups = {k: v for k, v in groups.items() if len(v) >= MIN_CHUNKS_PER_PROJECT}
    real_projects = [n for n in groups if n.lower() not in NON_PROJECT_HINTS
                      and n != "(loose scripts, no project folder)"]
    real_projects = sorted(real_projects, key=lambda n: -len(groups[n]))[:n_projects]
    print(f"Calibrating against {len(real_projects)} real projects: {real_projects}\n")

    VERIFIERS = {"v1_holistic": _verify_summary_claims, "v2_per_claim": _verify_summary_claims_v2}

    results = []  # each: dict(project, case, verifier, flagged, ...)
    for pi, project in enumerate(real_projects):
        print(f"[{pi+1}/{len(real_projects)}] {project} ...")
        samples = sample_project(engine, project, groups[project], seed=hash(project) % (2**31))
        if not samples:
            print("  (no readable samples, skipping)")
            continue
        samples_text = "\n\n".join(samples)

        try:
            clean_summary = generate_clean_summary(project, samples_text)
        except Exception as e:
            print(f"  summary generation failed: {e}, skipping")
            continue

        fabricated = FABRICATED_CLAIMS[pi % len(FABRICATED_CLAIMS)]
        corrupted_summary = clean_summary.rstrip(". ") + ". " + fabricated

        for case_name, summary in (("clean", clean_summary), ("corrupted", corrupted_summary)):
            for v_name, v_fn in VERIFIERS.items():
                flagged_list = v_fn(samples_text, summary)
                if flagged_list is None:
                    print(f"  [{v_name}/{case_name}] no model reachable, skipping this case")
                    continue
                is_flagged = len(flagged_list) > 0
                print(f"  [{v_name}/{case_name}] flagged={is_flagged}")
                results.append({
                    "project": project,
                    "case": case_name,
                    "verifier": v_name,
                    "expected_flag": (case_name == "corrupted"),
                    "actual_flag": is_flagged,
                    "injected_claim": fabricated if case_name == "corrupted" else None,
                    "summary": summary,
                })

    print("\n" + "=" * 60)
    print("  CALIBRATION RESULT (head-to-head, identical cases)")
    print("=" * 60)

    all_stats = {}
    for v_name in VERIFIERS:
        vr = [r for r in results if r["verifier"] == v_name]
        tp = sum(1 for r in vr if r["case"] == "corrupted" and r["actual_flag"])
        fn = sum(1 for r in vr if r["case"] == "corrupted" and not r["actual_flag"])
        tn = sum(1 for r in vr if r["case"] == "clean" and not r["actual_flag"])
        fp = sum(1 for r in vr if r["case"] == "clean" and r["actual_flag"])
        precision = tp / (tp + fp) if (tp + fp) else float("nan")
        recall = tp / (tp + fn) if (tp + fn) else float("nan")
        accuracy = (tp + tn) / len(vr) if vr else float("nan")
        all_stats[v_name] = {"tp": tp, "fn": fn, "tn": tn, "fp": fp,
                              "precision": precision, "recall": recall, "accuracy": accuracy}

        print(f"\n{v_name}: cases={len(vr)}")
        print(f"  TP={tp}  FN={fn}  TN={tn}  FP={fp}")
        print(f"  precision = {precision:.2f}   recall = {recall:.2f}   accuracy = {accuracy:.2f}")
        if fn:
            print(f"  MISSED (recall failures):")
            for r in vr:
                if r["case"] == "corrupted" and not r["actual_flag"]:
                    print(f"    - {r['project']}: \"{r['injected_claim']}\"")
        if fp:
            print(f"  FALSE POSITIVES (precision failures):")
            for r in vr:
                if r["case"] == "clean" and r["actual_flag"]:
                    print(f"    - {r['project']}")

    out_path = Path(__file__).resolve().parent / "consensus_calibration_results.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump({"results": results, "stats": all_stats}, f, indent=2)
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    main()
